# Publish GitHub workflow artifacts tutorial example
name: Publish GitHub Actions Artifacts Example
on:
  push:
    branches: [ main ]
jobs:
  github-actions-environment-variables-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: List of the GitHub Actions environment variables on Windows
        run: env

  github-actions-environment-variables-windows:
    runs-on: windows-latest
    steps:
      - name: Ubuntu GitHub Actions environment variables List
        run: env

  github-actions-environment-variables-macos:
    runs-on: macos-latest
    steps:
      - name: MacOs List of GitHub Actions environment variables
        run: env

  built-in-variables:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJSON(job) }}
        run: echo "$JOB_CONTEXT"

      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJSON(steps) }}
        run: echo "$STEPS_CONTEXT"

      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJSON(runner) }}
        run: echo "$RUNNER_CONTEXT"

      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJSON(strategy) }}
        run: echo "$STRATEGY_CONTEXT"

      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJSON(matrix) }}
        run: echo "$MATRIX_CONTEXT"
